name = "ForceImport"
uuid = "9dda63f9-cce7-5873-89fa-eccbb2fffcde"
repo = "https://github.com/chakravala/ForceImport.jl.git"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
